version: '3'

services:
  web:
    build: .
    container_name: app01
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis01:6379/0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: 'redis'
    container_name: redis01
    ports:
      - '6379:6379'

  worker:
    build:
      context: ./flask-celery
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis01:6379/0
    volumes:
      - ./flask-celery:/flask-celery
    depends_on:
      - redis

  monitor:
    build:
      context: ./flask-celery
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis01:6379/0
    depends_on:
      - redis
